export default [
  ['testSuiteStarted', 'src/test/sequence-check/async-2.spec.ts'],
  ['testSuiteStarted', 'Example sequence-check async file 2'],
  ['testSuiteStarted', 'Test log with async'],
  ['testStarted', 'should log 2 times'],
  ['testStdOut', 'should log 2 times'],
  ['testStdOut', 'should log 2 times'],
  ['testFinished', 'should log 2 times'],
  ['testStarted', 'should log after 1000 ms'],
  ['testStdOut', 'should log after 1000 ms'],
  ['testFinished', 'should log after 1000 ms'],
  ['testSuiteFinished', 'Test log with async'],
  ['testSuiteFinished', 'Example sequence-check async file 2'],
  ['testSuiteFinished', 'src/test/sequence-check/async-2.spec.ts'],
]
