export default [
  ['testSuiteStarted', 'src/test/sequence-check/sync.spec.ts'],
  ['testSuiteStarted', 'Example sequence-check sync file'],
  ['testSuiteStarted', 'Performance nested suit'],
  ['testStarted', 'should return true'],
  ['testMetadata', 'sourceFile'],
  ['testMetadata', 'vitestFullName'],
  ['testFinished', 'should return true'],
  ['testStarted', 'should return false'],
  ['testMetadata', 'sourceFile'],
  ['testMetadata', 'vitestFullName'],
  ['testFailed', 'should return false'],
  ['testFinished', 'should return false'],
  ['testSuiteFinished', 'Performance nested suit'],
  ['testSuiteFinished', 'Example sequence-check sync file'],
  ['testSuiteFinished', 'src/test/sequence-check/sync.spec.ts'],
]
